# Generated by Django 5.2.9 on 2026-01-07 05:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('post_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('short_description', models.CharField(max_length=200)),
                ('status', models.CharField(default='active', max_length=20)),
                ('visibility', models.CharField(default='verified_only', max_length=30)),
                ('nda_required', models.BooleanField(default=True)),
                ('post_valid_till', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='InvestorPostDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_title', models.CharField(max_length=100)),
                ('investor_type', models.CharField(max_length=50)),
                ('preferred_location', models.CharField(max_length=100)),
                ('investment_min', models.BigIntegerField()),
                ('investment_max', models.BigIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('stage_preference', models.CharField(max_length=100)),
                ('industries', models.TextField()),
                ('investment_style', models.CharField(max_length=50)),
                ('expected_return', models.CharField(max_length=50)),
                ('investment_horizon', models.CharField(max_length=50)),
                ('value_addition', models.TextField()),
                ('past_experience', models.CharField(max_length=50)),
                ('founder_preference', models.CharField(max_length=50)),
                ('minimum_validation', models.CharField(max_length=50)),
                ('ticket_strategy', models.CharField(max_length=50)),
                ('linkedin_url', models.TextField(blank=True, null=True)),
                ('website_url', models.TextField(blank=True, null=True)),
                ('active_deal_status', models.CharField(max_length=30)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'db_table': 'investor_post_details',
            },
        ),
        migrations.CreateModel(
            name='EntrepreneurPostDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('target_users', models.TextField()),
                ('funding_min', models.BigIntegerField(null=True)),
                ('funding_max', models.BigIntegerField(null=True)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('use_of_funds', models.TextField()),
                ('investor_return', models.CharField(max_length=50)),
                ('founder_name', models.CharField(max_length=100)),
                ('founder_type', models.CharField(max_length=30)),
                ('team_size', models.IntegerField()),
                ('founder_background', models.CharField(max_length=50)),
                ('business_description', models.CharField(max_length=500)),
                ('pitch_deck_url', models.TextField(blank=True, null=True)),
                ('website_url', models.TextField(blank=True, null=True)),
                ('linkedin_url', models.TextField(blank=True, null=True)),
                ('twitter_url', models.TextField(blank=True, null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'db_table': 'entrepreneur_post_details',
            },
        ),
        migrations.CreateModel(
            name='PostNDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nda_file_url', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'db_table': 'post_ndas',
            },
        ),
        migrations.CreateModel(
            name='NDAAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('viewer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('viewer_device', models.TextField(blank=True, null=True)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nda_acceptances', to='posts.post')),
            ],
            options={
                'db_table': 'nda_acceptances',
                'unique_together': {('post', 'viewer')},
            },
        ),
    ]
