# Generated by Django 5.2.9 on 2026-01-07 06:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0002_alter_ndaacceptance_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndaacceptance',
            name='post',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='ndaacceptance',
            name='viewer',
            field=models.ForeignKey(db_column='viewer_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_posts', to='accounts.user')),
            ],
            options={
                'db_table': 'post_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('like', 'Like'), ('save', 'Save'), ('share', 'Share'), ('view', 'View')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_engagements', to='accounts.user')),
            ],
            options={
                'db_table': 'post_engagements',
                'unique_together': {('post', 'user', 'action')},
            },
        ),
    ]
