# Generated by Django 5.2.9 on 2026-01-07 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_entrepreneurpostdetails_business_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='founder_background',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='founder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='founder_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='funding_max',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='funding_min',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='investor_return',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='linkedin_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='pitch_deck_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='target_users',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='team_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='twitter_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='use_of_funds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurpostdetails',
            name='website_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='active_deal_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='expected_return',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='founder_preference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='industries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='investment_horizon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='investment_max',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='investment_min',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='investment_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='investor_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='investor_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='linkedin_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='minimum_validation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='past_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='stage_preference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='ticket_strategy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='value_addition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorpostdetails',
            name='website_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrepreneurpostdetails',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='investorpostdetails',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AlterModelTable(
            name='entrepreneurpostdetails',
            table='entrepreneur_post_details',
        ),
        migrations.AlterModelTable(
            name='investorpostdetails',
            table='investor_post_details',
        ),
    ]
