# Generated by Django 5.2.9 on 2026-01-07 05:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password_hash', models.TextField()),
                ('role', models.CharField(max_length=20)),
                ('native_country', models.CharField(max_length=100)),
                ('native_state', models.CharField(max_length=100)),
                ('native_city', models.CharField(max_length=100)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('subscription_status', models.CharField(default='pending', max_length=20)),
                ('legal_consent', models.BooleanField(default=False)),
                ('legal_consent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('verify_email', 'verify_email'), ('verify_phone', 'verify_phone'), ('reset_password', 'reset_password')], max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_otps',
            },
        ),
    ]
