# Generated by Django 5.2.9 on 2026-01-08 05:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reporter_id', models.UUIDField()),
                ('reported_user_id', models.UUIDField(blank=True, null=True)),
                ('target_type', models.CharField(choices=[('user', 'User'), ('post', 'Post'), ('chat', 'Chat'), ('nda', 'NDA')], max_length=50)),
                ('target_id', models.UUIDField()),
                ('reason', models.CharField(choices=[('fake_profile', 'Fake Profile'), ('idea_theft', 'Idea Theft'), ('harassment', 'Harassment'), ('spam', 'Spam'), ('fraud', 'Fraud'), ('nda_violation', 'NDA Violation'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
